### ISSUE TITLE
Design mobile

### ISSUE THREAD

**Issue by mespiga** [Coderhat/website_angularjs#3]
Adicionar ao design mobile existente na drive com o nome coderhat_mobile o seguinte:
* matriz skills

1h

**Comment by gracianasousa** [comment]
Done. 
Coloquei imagens na drive, na pasta logos ( logos das skills).

**Comment by filipemoraes** [comment]
As paginas mobile (nacional/international) foram concluídas.
Devido a versão mobile ser diferente da versão desktop (navegação, design), a versão mobile só abre em dispositivos mobile, não será possível visualizar no desktop.

**Comment by mespiga** [comment]
Duplicate #9
