### ISSUE TITLE
Desenhar cartao de cidadão / passaporte

### ISSUE THREAD

**Issue by mespiga** [Coderhat/website_angularjs#4]
Desenhar cartao de cidadão / passaporte para detalhe de cada pessoa da team.

4h

**Comment by gracianasousa** [comment]
Done. Aprovado pelo Miguel.
Já coloquei as imagens na Drive, como ja te referi hoje de tarde Filipe.

**Comment by filipemoraes** [comment]
Implementado.
Na imagem do cartão, é necessário inserir o logotipo da empresa, a versão exportada para PNG não incluiu o logotipo.
Sugiro alterar a imagem que está na pasta "images" do projeto (http://www.angularjs.coderhat.com/images/card.png), uma vez que alterei o tamanho, removi as bordas e centralizei a imagem.
